function Hd = butterLow30
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 13-Jul-2017 12:11:52

Fpass = 30;   % Passband Frequency
Fstop = 33;   % Stopband Frequency
Apass = 1;    % Passband Ripple (dB)
Astop = 40;   % Stopband Attenuation (dB)
Fs    = 250;  % Sampling Frequency

h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);

Hd = design(h, 'butter', ...
    'MatchExactly', 'passband', ...
    'SystemObject', true);


